spring.application.name=kriterika
spring.datasource.url=jdbc:postgresql://localhost:5433/kriterika
spring.datasource.username=admin
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080

kinopoisk.api.url=https://kinopoiskapiunofficial.tech
kinopoisk.api.key=YOUR_API_KEY_HERE
jwt.secret=KriterikaSecretKeyForJwtTokenGeneration2024
jwt.expiration=86400000
